title       = "alphafold"
baseURL     = "https://alphafold-cli.tamnd.com/"
description = "A command line for alphafold."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/alphafold-cli"
